// ============================================================
// StudentHub — Tool Registry
// ============================================================

import { Tool, ToolCategory } from '@/types';

export const TOOLS: Tool[] = [
  {
    id: 'document-converters',
    name: 'Document Converters',
    slug: 'document-converters',
    description: 'Convert documents between popular file formats quickly and securely.',
    icon: '🔄',
    category: 'documents',
    categories: ['documents'],
    status: 'available',
    path: '/tools/document-converters',
    color: '#0284c7',
  },
  {
    id: 'image-converters',
    name: 'Image Converters',
    slug: 'image-converters',
    description: 'Convert images across JPG, PNG, WebP, HEIC, GIF, BMP, TIFF, and SVG quickly.',
    icon: '🖼️',
    category: 'documents',
    categories: ['documents'],
    status: 'available',
    path: '/tools/image-converters',
    color: '#8b5cf6',
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    slug: 'pdf',
    description: 'Merge, split, convert, reorder, and compress your PDF files in your browser.',
    icon: '📋',
    category: 'documents',
    categories: ['documents'],
    status: 'available',
    path: '/tools/pdf',
    color: '#2563eb',
  },
  {
    id: 'resume',
    name: 'Resume Generator',
    slug: 'resume',
    description: 'Build ATS-friendly, professional resumes using StudentHub resume templates.',
    icon: '📄',
    category: 'career',
    categories: ['career', 'documents'],
    status: 'coming-soon',
    path: '/tools/resume',
    color: '#7c3aed',
  },
  {
    id: 'calculator',
    name: 'Percentage Calculator',
    slug: 'calculator',
    description: 'Calculate marks percentage, semester CGPA to percentage, and academic scores.',
    icon: '🧮',
    category: 'academic',
    categories: ['academic'],
    status: 'coming-soon',
    path: '/tools/calculator',
    color: '#059669',
  },
  {
    id: 'attendance',
    name: 'Attendance Calculator',
    slug: 'attendance',
    description: 'Track your attendance and calculate how many classes you need to attend for 75%+ eligibility.',
    icon: '📅',
    category: 'academic',
    categories: ['academic', 'planning'],
    status: 'coming-soon',
    path: '/tools/attendance',
    color: '#16a34a',
  },
  {
    id: 'notes',
    name: 'Notes',
    slug: 'notes',
    description: 'Upload, organize and access all your study notes and flashcards in one place.',
    icon: '📝',
    category: 'study',
    categories: ['study'],
    status: 'coming-soon',
    path: '/tools/notes',
    color: '#d97706',
  },
  {
    id: 'notes-search',
    name: 'Notes Search',
    slug: 'notes-search',
    description: 'Search your uploaded study materials and quickly find definitions and formulas.',
    icon: '🔍',
    category: 'study',
    categories: ['study'],
    status: 'coming-soon',
    path: '/tools/notes/search',
    color: '#0891b2',
  },
  {
    id: 'summary',
    name: 'PDF Summary',
    slug: 'summary',
    description: 'Turn long PDFs into concise summaries, key points, and chapter takeaways.',
    icon: '✨',
    category: 'study',
    categories: ['study', 'documents'],
    status: 'coming-soon',
    path: '/tools/summary',
    color: '#7c3aed',
  },
  {
    id: 'mindmap',
    name: 'Mind Map Generator',
    slug: 'mindmap',
    description: 'Turn complex syllabus topics and study concepts into visual interactive mind maps.',
    icon: '🧠',
    category: 'study',
    categories: ['study'],
    status: 'coming-soon',
    path: '/tools/mindmap',
    color: '#db2777',
  },
  {
    id: 'questions',
    name: 'Question Preparation',
    slug: 'questions',
    description: 'Generate and organize exam preparation question banks and practice tests.',
    icon: '❓',
    category: 'study',
    categories: ['study'],
    status: 'coming-soon',
    path: '/tools/questions',
    color: '#dc2626',
  },
  {
    id: 'search',
    name: 'Study Search',
    slug: 'search',
    description: 'Find curated academic resources across textbooks, YouTube, and your study materials.',
    icon: '🌐',
    category: 'study',
    categories: ['study'],
    status: 'coming-soon',
    path: '/tools/search',
    color: '#0369a1',
  },
  {
    id: 'timetable',
    name: 'Timetable Generator',
    slug: 'timetable',
    description: 'Create and organize your balanced weekly academic timetable and study routine.',
    icon: '🗓️',
    category: 'planning',
    categories: ['planning'],
    status: 'coming-soon',
    path: '/tools/timetable',
    color: '#7c3aed',
  },
];

export const TOOL_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'study', label: 'Study' },
  { id: 'documents', label: 'Documents' },
  { id: 'academic', label: 'Academic' },
  { id: 'planning', label: 'Planning' },
  { id: 'career', label: 'Career' },
] as const;

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  if (category === 'all') return TOOLS;
  return TOOLS.filter(
    (t) => t.category === category || (t.categories && t.categories.includes(category as ToolCategory))
  );
}
